@extends('layouts.manager')

@section('content')

<div class="bg-white shadow rounded-xl p-8">

<h2 class="text-2xl font-bold mb-6">

{{ $report->report_name }}

</h2>

<p class="mb-3">

<strong>Employee:</strong>

{{ $report->employee->name }}

</p>

<p class="mb-3">

<strong>Generated By:</strong>

{{ $report->manager->name }}

</p>

<p class="mb-3">

<strong>Report Type:</strong>

{{ ucfirst($report->report_type) }}

</p>

<p class="mb-3">

<strong>Date:</strong>

{{ \Carbon\Carbon::parse($report->generated_at)->format('d M Y H:i') }}

</p>

<hr class="my-6">

<p>

{{ $report->description }}

</p>

</div>

@endsection