@extends('layouts.employee')

@section('content')

<div class="max-w-4xl mx-auto bg-white shadow rounded-xl p-8">

    <h2 class="text-2xl font-bold mb-6">
        {{ $report->report_name }}
    </h2>

    <div class="space-y-4">

        <div>
            <strong>Report Type:</strong>
            {{ ucfirst($report->report_type) }}
        </div>

        <div>
            <strong>Generated By:</strong>
            {{ $report->manager?->name ?? 'Manager' }}
        </div>

        <div>
            <strong>Date Generated:</strong>
            {{ \Carbon\Carbon::parse($report->generated_at)->format('d M Y H:i') }}
        </div>

        <div>
            <strong>Description</strong>

            <div class="mt-2 border rounded-lg p-4 bg-gray-50">
                {{ $report->description ?? 'No description available.' }}
            </div>
        </div>

    </div>

    <div class="mt-8">
        <a href="{{ route('employee.reports') }}"
           class="bg-green-700 text-white px-6 py-2 rounded-lg hover:bg-green-800">
            ← Back to Reports
        </a>
    </div>

</div>

@endsection